In [33]:
import numpy as np

In [34]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [35]:
type(a)

numpy.ndarray

- Basic Operation of Array

In [36]:
print(a+b)
print(a-b)
print(a*b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]


In [37]:
#creating a 2D array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr)

NameError: name 'arr' is not defined

In [23]:
#creating a 3D array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
print(arr1.shape) #shape of the array

(2, 3)


In [26]:
print(arr1.ndim) #dimension of the array

2


In [27]:
print(arr1.dtype)

int64


In [28]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [17]:
np.random.randint(10,30, size=(3,3))

array([[12, 26, 14],
       [29, 15, 29],
       [26, 16, 11]], dtype=int32)

In [19]:
x=np.array([[7,2,3],[2,5,3],[3,5,1]])
y=np.array([[1,8,3],[3,7,2],[2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 3]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [20]:
print(x+y)
print(x-y)
print(x*y)

[[ 8 10  6]
 [ 5 12  5]
 [ 5 10  4]]
[[ 6 -6  0]
 [-1 -2  1]
 [ 1  0 -2]]
[[ 7 16  9]
 [ 6 35  6]
 [ 6 25  3]]


In [21]:
print(x@y)#matrix multiplication

[[19 85 34]
 [23 66 25]
 [20 64 22]]


In [23]:
np.dot(x,y)#matrix multiplication

array([[19, 85, 34],
       [23, 66, 25],
       [20, 64, 22]])

In [22]:
x.prod()#product of all elements in the array

np.int64(18900)

In [24]:
x.mean()#mean of all element in the array

np.float64(3.4444444444444446)

In [25]:
y.mean()#mean of all element in the array

np.float64(3.7777777777777777)

In [26]:
round(y.mean())

4

In [27]:
x.mean(axis=0)#mean of each column

array([4.        , 4.        , 2.33333333])

In [28]:
y.mean(axis=1) #mean of each row

array([4.        , 4.        , 3.33333333])

In [29]:
print(x.sum())
print(x.var())#var is used for variance.
print(x.std())

31
3.1358024691358026
1.7708197167232476


In [30]:
a=np.array([1,2,3,4,6,5,7])
print(np.percentile(a,50))
print(np.percentile (a,25))
print(np.percentile(a,75))

4.0
2.5
5.5


In [39]:
b = np.random.randint(11,100, (4,4))
print(b)

[[86 91 22 68]
 [24 82 81 93]
 [33 56 59 50]
 [38 27 23 90]]


In [45]:
print('8*2')
print(b.reshape(8,2))

8*2
[[86 91]
 [22 68]
 [24 82]
 [81 93]
 [33 56]
 [59 50]
 [38 27]
 [23 90]]


In [46]:
print('2*8')
print(b.reshape(2,8))

2*8
[[86 91 22 68 24 82 81 93]
 [33 56 59 50 38 27 23 90]]


In [41]:
print(b.reshape(4,4))

[[86 91 22 68]
 [24 82 81 93]
 [33 56 59 50]
 [38 27 23 90]]


In [42]:
print(b[0])#first row
print(b[0,2])#first row,third column
print(b[-1])#last row
print(b[1:3])#second and third row
print(b[3:])#last row

[86 91 22 68]
22
[38 27 23 90]
[[24 82 81 93]
 [33 56 59 50]]
[[38 27 23 90]]
