In [18]:
import numpy as np

In [19]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [20]:
type(a)

numpy.ndarray

- Basic Operation of Array

In [21]:
print(a+b)
print(a-b)
print(a*b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]


In [22]:
#creating a 2D array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
#creating a 3D array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
print(arr1.shape) #shape of the array

(2, 3)


In [26]:
print(arr1.ndim) #dimension of the array

2


In [27]:
print(arr1.dtype)

int64


In [28]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])